CREATE EXTENSION IF NOT EXISTS pg_stat_statements;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE categories (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL
);
CREATE TABLE products (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    price numeric(14,2) NOT NULL CHECK (price > 0),
    category_id integer NOT NULL REFERENCES categories(id),
    stock integer NOT NULL CHECK (stock >= 0)
);
CREATE INDEX products_category_id_idx ON products(category_id);
CREATE TABLE users (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email text NOT NULL UNIQUE,
    password_hash text NOT NULL
);
CREATE TABLE orders (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL REFERENCES users(id),
    status text NOT NULL,
    total numeric(18,2) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);
-- Индекса orders.user_id НАМЕРЕННО нет: его добавят в уроке 11.3.
CREATE TABLE order_items (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id integer NOT NULL REFERENCES orders(id),
    product_id integer NOT NULL REFERENCES products(id),
    qty integer NOT NULL CHECK (qty > 0),
    price numeric(14,2) NOT NULL CHECK (price > 0)
);
CREATE INDEX order_items_order_id_idx ON order_items(order_id);
